[tasks]

# Start only the Redis service defined in docker-compose.yml
[tasks.redis-up]
run = "docker compose -f docker/docker-compose.yml up -d redis"

[tasks.docker-up]
run = "docker compose -f docker/docker-compose.yml up -d"

# Stop all services (optional convenience)
[tasks.docker-down]
run = "docker compose -f docker/docker-compose.yml down"

# Run Redis benchmark against the running redis container
# Depends on redis being up; will start it if not already running
[tasks.redis-bench]
depends = ["redis-up"]
run = "docker exec redis redis-benchmark -t zadd -n 10000000 -c 50 -d 16 -k 1 -r 1000000000 -P 10 --threads 10"  # 512KB 524288

[tasks.start-producer]
run = "docker compose -f docker/docker-compose.yml exec -it data-generator python _04_main.py start-producer"

[tasks."flink:build"]
description = "Build Flink JAR package"
run = "cd flink-jobs && mvn clean package -DskipTests"


[tasks."flink:run"]
description = "Run building leaderboard job"
run = "docker compose -f docker/docker-compose.yml exec -it jobmanager flink run -c jobs.LeaderBoardBuilder /opt/flink/jobs/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:test"]
description = "Run Flink tests"
run = "cd flink-jobs && mvn test"

# [tasks."spark:run"]
# description = "Run Spark leaderboard processor on cluster"
# depends = ["docker-up"]
# run = """
# docker compose -f docker/docker-compose.yml exec -it spark-master `
#   spark-submit `
#   --master spark://spark-master:7077 `
#   /opt/spark/jobs/leaderboard_processor.py `
#   /opt/spark/jobs/fixed-dataset.parquet `
#   /opt/spark/jobs/output/leaderboard_snapshots `
#   --window-size 5 `
#   --top-n 10 `
#   --ttl 30 `
#   --snapshot-interval 7
# """

# [tasks."spark:run2"]
# description = "Run Spark leaderboard processor on cluster"
# depends = ["docker-up"]
# run = "docker compose -f docker/docker-compose.yml exec -it spark-master spark-submit --master spark://spark-master:7077 /opt/spark/jobs/leaderboard_processor.py /opt/spark/jobs/fixed-dataset.parquet /opt/spark/jobs/output/leaderboard_snapshots --window-size 5 --top-n 10 --ttl 30 --snapshot-interval 7"