{
 "title": "New dashboard",
 "time": { "from": "2027-01-08T00:00:00.000Z", "to": "2027-01-09T03:00:00.000Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Top customer by avg tx amt by time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH latest_events AS (\r\n    SELECT *\r\n    FROM \"fintech_analytics\".\"customer_transaction_metrics\"\r\n    WHERE eventTime = (\r\n        SELECT MAX(eventTime)\r\n        FROM \"fintech_analytics\".\"customer_transaction_metrics\"\r\n    )\r\n)\r\nSELECT customerId,\r\n       averageAmount,\r\n       eventTime\r\nFROM latest_events\r\nORDER BY averageAmount DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Top bussinessType by Revenue",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT businessType, totalRevenue FROM \"fintech_analytics\".\"business_type_performance\" LIMIT 10"
    }
   ]
  },
  {
   "title": "Fraud transaction by hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT hour, alertCount FROM \"fintech_analytics\".\"fraud_alerts_timeline\" LIMIT 100"
    }
   ]
  },
  {
   "title": "Customer Tier",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT currentTier, customerCount  FROM \"fintech_analytics\".\"customer_analytics_dashboard\" "
    }
   ]
  }
 ]
}