{
 "title": "Flink ↔ Kafka Throughput & Subtasks",
 "tags": [
  "flink",
  "kafka",
  "prometheus",
  "throughput"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond, job_name)"
   },
   {
    "name": "group",
    "query": "label_values(kafka_consumergroup_lag, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Producer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (\r\n  rate(kafka_topic_partition_current_offset{topic=~\"test_performance|fintech.customer_transaction_metrics_running\"}[10s])\r\n)\r\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Flink Consume Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (\r\n  rate(kafka_consumergroup_current_offset{topic=~\"test_performance|fintech.customer_transaction_metrics_running\"}[10s])\r\n)",
     "legendFormat": "{{consumergroup}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Flink Output EPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (task_name) (\r\n  flink_taskmanager_job_task_numRecordsOutPerSecond{job_name=\"Customer_Transaction_Metrics_Running_Job___Dump_Sink\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Input EPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "\r\nsum by (task_name) (\r\n  flink_taskmanager_job_task_numRecordsInPerSecond{job_name=\"Customer_Transaction_Metrics_Running_Job___Dump_Sink\"}\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Writer Latency per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{operator_name=\"Customer_Transaction_Metrics_Running_Output:_Writer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}