global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:9249']

  - job_name: 'flink-taskmanagers'
    static_configs:
      - targets: ['taskmanager:9249']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

