apiVersion: 1
datasources:
  - name: Redis
    type: redis-datasource
    uid: redis
    access: proxy
    isDefault: false
    url: redis://redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
    secureJsonData:
      password: ""


